#pragma once

//return error codes
#define EXIT_POWEROFF 0
#define EXIT_BOOTLOADER_TOO_BIG 0x1
#define EXIT_ILLEGAL_INSTRUCTION 0x2
#define EXIT_ILLEGAL_MRET 0x3
#define EXIT_ILLEGAL_SRET 0x4
#define EXIT_WFI 0x5
#define EXIT_INVALID_SATP_MODE 0x10
#define EXIT_UNSUPPORTED_READ_SIZE 0x11
#define EXIT_UNSUPPORTED_WRITE_SIZE 0x12
#define EXIT_TOO_MANY_MEMORY_RANGES 0x13
#define EXIT_CANNOT_ALLOCATE_VM_MEMORY 0x14
#define EXIT_CANNOT_LOAD_TEST_BINARY 0x1000
#define EXIT_TEST_FAILED 0x1001