#pragma once
#define SBI_SET_TIMER 0
#define SBI_CONSOLE_PUTCHAR 1
#define SBI_CONSOLE_GETCHAR 2
#define SBI_CLEAR_IPI 3
#define SBI_SEND_IPI 4
#define SBI_REMOTE_FENCE_I 5
#define SBI_REMOTE_SFENCE_VMA 6
#define SBI_REMOTE_SFENCE_VMA_ASID 7
#define SBI_SHUTDOWN 8

#define SBI_ARG0_REG 10 //A0 = X10
#define SBI_ARG1_REG 11 //A1 = X11
#define SBI_ARG2_REG 12 //A2 = X11
#define SBI_ARG3_REG 13 //A3 = X11
#define SBI_WHICH 17  //A7 = X11